### ISSUE TITLE
Generated bundle.js file is bloated

### ISSUE THREAD

**Issue by izeau** [jadejs/react-jade#49] opened 2015-06-03 12:47 UTC
Hi,

This project would be awesome if it weren't for one thing: react-jade seems to force browserify to bundle a ton of dependencies – including React. I'm new to browserify so maybe I'm doing something wrong, but the `-t react-jade` flag itself adds about 600 KB to the file size.

I'm using this command: `browserify src/index.js -x react -t react-jade > www/bundle.js`

```js
// src/index.js
"use strict";

var React = require("react");
var App = require("./components/app/index.js");

React.render(
  React.createElement(App),
  document.body
);
```

```js
// src/components/app/index.js
"use strict";

var React    = require("react");
var jade     = require("react-jade");
var template = jade.compileFile(__dirname + "/template.jade");

module.exports = React.createClass({
  render: function() {
    return template();
  }
});
```

```jade
// src/components/app/template.jade
#app
```

##### versions

  * browserify: 10.2.3
  * react-jade: 2.4.0

**Comment by izeau** [comment] 2015-06-03 13:40
This doesn't happen if I set the `globalReact` option!

(I changed my command to `browserify src/index.js -x react -t [ react-jade --globalReact ] > www/bundle.js`.)

**Comment by jeromew** [comment] 2015-06-03 14:39
thanks for finding the fix we forgot to document this flag.

what would be a good way to explain this according to you @izeau and where should be add it ?

**Comment by izeau** [comment] 2015-06-09 14:17
I think react-jade is already doing more than what's strictly required for it to work. Why not just `require("react")` inside the template function?

**Comment by ForbesLindesay** [comment] 2015-07-16 15:14
Closing as a duplicate of #30

**Closed by ForbesLindesay** 2015-07-16 15:14 UTC
